nome = str(input('DIGITE SEU NOME: ')).strip()
print('-' * 5,'analisando seu nome...','-' * 5)
print('seu nome em maiusculas é ', nome.upper())
print('seu nome em minusculas é ', nome.lower())
print('seu nome tem {} letras'.format(len(nome)-nome.count(' ')))
#print('seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print(separa)
print('seu primeiro nome é {} e ele tem {} letras '.format(separa[0],len(separa[0])))
